language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install argparse catkin-pkg empy nose
# command to run tests
script:
  - nosetests test/unit_tests test/local_tests
notifications:
  email: false
