Package: catkin
Version: 3.4.5
Section: misc
Priority: extra
Architecture: all
Depends: ${misc:Depends} python-empy, cmake, make, lsb-release
Build-Depends: debhelper (>= 7), cmake, gcc, make, python-empy, lsb-release
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: catkin
Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
