Catkin-ProjectName: catkin
Description: Willow Garage low-level build system macros and infrastructure.
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Brian Gerkey
Maintainer: Brian Gerkey <gerkey@willowgarage.com>
Homepage: http://www.ros.org

Version: 0.3.23

Depends: cmake,
  python-setuptools,
  python-empy,
  python-argparse,
  python-yaml

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: cmake

